
GET  http://localhost:1808
###

GET  http://localhost:1808/order/list-all-orders
###

POST http://localhost:1808/order/create-new-order
Content-Type: application/json

{
    "SID": "SID02",
    "reportName": "Order"
}
###

POST http://localhost:1808/order/update-order-form
Content-Type: application/json

{
    "reportId": "66e532935a417d8349c19b39",
    "field": "qrCodeUrl",
    "value": "sourabhraghavendra.in"
}

###

POST http://localhost:1808/order/retrieve-order
Content-Type: application/json

{
    "orderId": "66e532935a417d834c19b39",
    "reportId": "66e532935a417d8349c19b3c",
    "reportName": "IncomingAlert"
}

###

POST http://localhost:1808/order/update-report-value
Content-Type: application/json

{
    "orderId": "66e532935a417d8349c19b39",
    "reportId": "66e532935a417d8349c19b3c",
    "reportName": "IncomingAlert",
    "field": "salesApproval",
    "value": "true"
}