
GET  http://localhost:1808
###

GET  http://localhost:1808/order/list-all-orders
###

POST http://localhost:1808/order/create-new-order
Content-Type: application/json

{
    "SID": "SID0",
    "reportName": "Order"
}
###

POST http://localhost:1808/order/update-order-form
Content-Type: application/json

{
    "reportId": "66e40d498f3f7a11af0066a7",
    "field": "customerName",
    "value": "turbojet"
}

###

POST http://localhost:1808/order/retrieve-order
Content-Type: application/json

{
    "orderId": "66e40d498f3f7a11af0066a7",
    "reportId": "66e40d498f3f7a11af0066ac",
    "reportName": "CheckSheet"
}